### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by Running-z** [idr-contrib/community#13] opened 2018-07-11 09:19 UTC
Hello, I am getting the following error when I use your example "IDR_API_example_script.ipynb"
:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-26-5b2416798de0> in <module>()
     23     payload = {'id': batch}
     24     print("payload is:", payload)
---> 25     for iid, thumb in session.get(THUMBNAILS_URL, params=payload).json().iteritems():
     26         _thumbnails[long(iid)] = thumb
     27 print("-thumbnails is:", _thumbnails)

AttributeError: 'dict' object has no attribute 'iteritems'

```

Can you tell me why? My python version is 3.5

**Comment by sbesson** [comment] 2018-07-11 09:24
Thanks @Running-z. This seems to be a duplicate of the issue raised in https://github.com/IDR/idr-notebooks/issues/66. I'll close this in favor of the first opened issue where we can keep the discussion (did you see @manic's https://github.com/IDR/idr-notebooks/issues/66#issuecomment-404085792?).

**Closed as completed by sbesson** 2018-07-11 09:24 UTC

**Comment by Running-z** [comment] 2018-07-11 09:37
@sbesson 
I saw it, thanks
